POST http://localhost:8000/upload/file
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="1.jpg"


< E:\Picture\1.jpg
--WebAppBoundary--

type=1
###
